apiVersion: v1
kind: Service
metadata:
  labels:
    app: datomic
    role: transactor
  name: transactor
  namespace: datomic
spec:
  clusterIP: None
  ports:
  - name: datomic
    port: 4334
    protocol: TCP
    targetPort: datomic
  selector:
    app: datomic
    role: transactor
  sessionAffinity: None
  type: ClusterIP
