apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: cassandra
spec:
  clusterIP: None
  ports:
  - name: intra-node
    port: 7000
    protocol: TCP
    targetPort: intra-node
  - name: tls-intra-node
    port: 7001
    protocol: TCP
    targetPort: tls-intra-node
  - name: jmx
    port: 7199
    protocol: TCP
    targetPort: jmx
  selector:
    app: cassandra
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
    role: client
  name: cassandra-client
  namespace: cassandra
spec:
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: # {"$kpt-set":"authorized-networks"}
  - "0.0.0.0/0"
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: cql
  selector:
    app: cassandra
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer
