apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: cassandra
spec:
  clusterIP: None
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: cql
  - name: intra-node
    port: 7000
    protocol: TCP
    targetPort: intra-node
  - name: tls-intra-node
    port: 7001
    protocol: TCP
    targetPort: tls-intra-node
  - name: jmx
    port: 7199
    protocol: TCP
    targetPort: jmx
  selector:
    app: cassandra
  sessionAffinity: None
  type: ClusterIP
